[package]
name = "plomid-optimizer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Logical and physical query planning foundations for PLOMID."

[dependencies]

[lib]
path = "src/lib.rs"

[lints]
workspace = true
