[package]
name = "plomid-wal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Write-ahead log foundations for PLOMID."

[dependencies]
plomid-core = { workspace = true }
plomid-storage = { workspace = true }
tracing = "0.1"

[lib]
path = "src/lib.rs"

[lints]
workspace = true
