//
// © 2026 PLOMID Technology Solutions
//
// PLOMID
// Platform for Modern Intelligence and Data
//
// Author: Sainath Sapa
// GitHub: https://github.com/sainathsapa
//
// Licensed under the Apache License, Version 2.0;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//! Integration tests proving that the actual PLOMID engine (parser → catalog →
//! executor → storage → recovery) uses the `plomid-types` PostgreSQL type
//! system as the single authoritative type representation.

use plomid_executor::Executor;
use plomid_sql::{QueryResult, Value};
use plomid_txn::PlomidStorageEngine;
use plomid_types::TypeOid;

fn unique_engine(tag: &str) -> (std::path::PathBuf, std::path::PathBuf) {
    let storage = std::env::temp_dir().join(format!("plomid-typed-{tag}-{}", std::process::id()));
    let wal = std::env::temp_dir().join(format!("plomid-typed-{tag}-wal-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&storage);
    let _ = std::fs::remove_dir_all(&wal);
    (storage, wal)
}

fn exec<E: plomid_txn::StorageEngine>(executor: &mut Executor<E>, sql: &str) -> Vec<Vec<Value>> {
    match executor.execute(sql).expect("sql should execute") {
        QueryResult::Rows { rows, .. } => rows,
        other => panic!("expected rows, got {other:?}"),
    }
}

#[test]
fn wide_typed_ddl_insert_select_roundtrip() {
    let (storage, wal) = unique_engine("wide");
    let engine = PlomidStorageEngine::create(&storage, &wal, 32).unwrap();
    let mut executor = Executor::new(engine).unwrap();

    executor
        .execute(
            "CREATE TABLE test (
                a INTEGER,
                b BIGINT,
                c NUMERIC(20,5),
                d TEXT,
                e VARCHAR(100),
                f BOOLEAN,
                g DATE,
                h TIMESTAMP,
                i TIMESTAMPTZ,
                j UUID,
                k JSON,
                l JSONB,
                m BYTEA,
                n INTEGER[]
            );",
        )
        .unwrap();

    executor
        .execute(
            "INSERT INTO test VALUES (
                42, 9007199254740993, '123.45678', 'hello', 'typed', 'true',
                '2024-05-17', '2024-05-17 12:34:56', '2024-05-17 12:34:56+00',
                'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '{\"a\": 1}',
                '{\"a\": 1}', '\\x48656c6c6f', '{1,2,3}'
            );",
        )
        .unwrap();

    let rows = exec(&mut executor, "SELECT * FROM test;");
    assert_eq!(rows.len(), 1);
    let row = &rows[0];

    // Typed runtime representations, not generic strings.
    assert_eq!(row[0], Value::Int4(42));
    assert_eq!(row[1], Value::Int8(9_007_199_254_740_993));
    assert!(matches!(row[2], Value::Numeric(_)));
    assert_eq!(row[3], Value::Text("hello".into()));
    assert!(matches!(row[4], Value::VarChar(_)));
    assert_eq!(row[5], Value::Bool(true));
    assert!(matches!(row[6], Value::Date(_)));
    assert!(matches!(row[7], Value::Timestamp(_)));
    assert!(matches!(row[8], Value::Timestamptz(_)));
    assert!(matches!(row[9], Value::Uuid(_)));
    assert!(matches!(row[10], Value::Json(_)));
    assert!(matches!(row[11], Value::Jsonb(_)));
    assert_eq!(row[12], Value::Bytea(b"Hello".to_vec()));
    assert!(matches!(row[13], Value::Array { .. }));

    // Canonical PostgreSQL text output.
    assert_eq!(row[6].to_sql_text(), "2024-05-17");
    assert_eq!(row[9].to_sql_text(), "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11");
    assert_eq!(row[12].to_sql_text(), "\\x48656c6c6f");
    assert_eq!(row[13].to_sql_text(), "{1,2,3}");

    drop(executor);
    let _ = std::fs::remove_dir_all(&storage);
    let _ = std::fs::remove_dir_all(&wal);
}

#[test]
fn gui_style_create_table_updates_live_catalog_and_is_idempotent() {
    let (storage, wal) = unique_engine("gui-ddl");
    let engine = PlomidStorageEngine::create(&storage, &wal, 32).unwrap();
    let mut executor = Executor::new(engine).unwrap();

    executor
        .execute(
            "CREATE TABLE IF NOT EXISTS compatibility_users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email CHARACTER VARYING(255) NOT NULL,
                created_at TIMESTAMP WITHOUT TIME ZONE
            ) WITH (oids = false) TABLESPACE pg_default;",
        )
        .unwrap();
    // PostgreSQL's IF NOT EXISTS is a successful no-op on the same relation.
    executor
        .execute("CREATE TABLE IF NOT EXISTS compatibility_users (id INTEGER);")
        .unwrap();

    let QueryResult::Rows {
        columns,
        column_types,
        rows,
    } = executor
        .execute("SELECT * FROM compatibility_users;")
        .unwrap()
    else {
        panic!("expected table rows result");
    };
    assert_eq!(columns, vec!["id", "email", "created_at"]);
    assert_eq!(column_types.len(), 3);
    assert!(rows.is_empty());

    drop(executor);
    let _ = std::fs::remove_dir_all(&storage);
    let _ = std::fs::remove_dir_all(&wal);
}

#[test]
fn result_metadata_carries_postgres_type_oids() {
    let (storage, wal) = unique_engine("oids");
    let engine = PlomidStorageEngine::create(&storage, &wal, 32).unwrap();
    let mut executor = Executor::new(engine).unwrap();

    executor
        .execute("CREATE TABLE meta (i INTEGER, s TEXT, u UUID);")
        .unwrap();
    executor
        .execute("INSERT INTO meta VALUES (1, 'x', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11');")
        .unwrap();
    let QueryResult::Rows {
        columns,
        column_types,
        rows,
    } = executor.execute("SELECT i, s, u FROM meta;").unwrap()
    else {
        panic!("expected rows");
    };

    // columns.len() == column_types.len() == row.values.len()
    assert_eq!(columns.len(), 3);
    assert_eq!(column_types.len(), 3);
    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0].len(), columns.len());

    assert_eq!(column_types[0].unwrap().type_oid, TypeOid::INT4);
    assert_eq!(column_types[1].unwrap().type_oid, TypeOid::TEXT);
    assert_eq!(column_types[2].unwrap().type_oid, TypeOid::UUID);

    drop(executor);
    let _ = std::fs::remove_dir_all(&storage);
    let _ = std::fs::remove_dir_all(&wal);
}

#[test]
fn update_where_comparison_and_null() {
    let (storage, wal) = unique_engine("update");
    let engine = PlomidStorageEngine::create(&storage, &wal, 32).unwrap();
    let mut executor = Executor::new(engine).unwrap();

    executor
        .execute("CREATE TABLE t (id INTEGER, name TEXT);")
        .unwrap();
    executor
        .execute("INSERT INTO t VALUES (1, 'Alice');")
        .unwrap();
    executor
        .execute("INSERT INTO t VALUES (2, 'Bob');")
        .unwrap();

    // Comparison predicates route through plomid-types value equality.
    let rows = exec(&mut executor, "SELECT * FROM t WHERE name = 'Bob';");
    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0][0], Value::Int4(2));

    executor
        .execute("UPDATE t SET name = 'Bobby' WHERE id = 2;")
        .unwrap();
    let rows = exec(&mut executor, "SELECT * FROM t WHERE id = 2;");
    assert_eq!(rows[0][1].to_sql_text(), "Bobby");

    executor
        .execute("UPDATE t SET name = NULL WHERE id = 1;")
        .unwrap();
    let rows = exec(&mut executor, "SELECT * FROM t WHERE id = 1;");
    assert_eq!(rows[0][1], Value::Null);

    drop(executor);
    let _ = std::fs::remove_dir_all(&storage);
    let _ = std::fs::remove_dir_all(&wal);
}

#[test]
fn restart_and_recovery_preserve_typed_values() {
    let (storage, wal) = unique_engine("restart");
    {
        let engine = PlomidStorageEngine::create(&storage, &wal, 32).unwrap();
        let mut executor = Executor::new(engine).unwrap();
        executor
            .execute("CREATE TABLE t (id INTEGER, d DATE, j UUID, b BOOLEAN);")
            .unwrap();
        executor.execute("INSERT INTO t VALUES (7, '2024-12-31', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'false');").unwrap();
        // A committed transaction whose WAL must replay on open.
        executor.execute("BEGIN; INSERT INTO t VALUES (8, '2000-01-01', 'ffffffff-ffff-ffff-ffff-ffffffffffff', 'true'); COMMIT;").unwrap();
    }
    {
        let engine = PlomidStorageEngine::open(&storage, &wal, 32).unwrap();
        let mut executor = Executor::new(engine).unwrap();
        let rows = exec(&mut executor, "SELECT * FROM t;");
        assert_eq!(rows.len(), 2);
        let by_id = |id: i32| {
            rows.iter()
                .find(|row| row[0] == Value::Int4(id))
                .unwrap_or_else(|| panic!("missing row {id}"))
        };
        assert_eq!(by_id(7)[1].to_sql_text(), "2024-12-31");
        // 2024-12-31 is 9131 days after 2000-01-01 (the storage epoch).
        assert_eq!(by_id(7)[1], Value::Date(9_131));
        assert_eq!(
            by_id(7)[2].to_sql_text(),
            "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"
        );
        assert_eq!(by_id(8)[3], Value::Bool(true));
    }
}

#[test]
fn catalog_resolves_types_through_the_authoritative_registry() {
    let (storage, wal) = unique_engine("catalog");
    let engine = PlomidStorageEngine::create(&storage, &wal, 32).unwrap();
    let mut executor = Executor::new(engine).unwrap();

    // Every accepted alias resolves through the registry's canonical builtin.
    for ddl in [
        "CREATE TABLE a1 (id INTEGER, x INT);",
        "CREATE TABLE a2 (id INTEGER, x INT8);",
        "CREATE TABLE a3 (id INTEGER, x BOOL);",
        "CREATE TABLE a4 (id INTEGER, x INT4RANGE);",
        "CREATE TABLE a5 (id INTEGER, x UUID[]);",
    ] {
        let result = executor.execute(ddl);
        assert!(result.is_ok(), "{ddl} should resolve: {result:?}");
    }

    // Range and array columns resolve through the registry.
    executor
        .execute("INSERT INTO a4 VALUES (1, NULL);")
        .unwrap();
    executor
        .execute("INSERT INTO a5 VALUES (1, NULL);")
        .unwrap();
    let rows = exec(&mut executor, "SELECT * FROM a4;");
    assert_eq!(rows[0][1], Value::Null);
    let rows = exec(&mut executor, "SELECT * FROM a5;");
    assert_eq!(rows[0][1], Value::Null);

    drop(executor);
    let _ = std::fs::remove_dir_all(&storage);
    let _ = std::fs::remove_dir_all(&wal);
}

#[test]
fn live_postgres_catalog_tracks_gui_style_ddl() {
    let (storage, wal) = unique_engine("live-catalog");
    let engine = PlomidStorageEngine::create(&storage, &wal, 32).unwrap();
    let mut executor = Executor::new(engine).unwrap();

    executor.execute("CREATE SCHEMA app;").unwrap();
    executor
        .execute(
            "CREATE TABLE app.products (
                id BIGSERIAL PRIMARY KEY,
                sku TEXT NOT NULL UNIQUE,
                price NUMERIC(12,2) NOT NULL
            );",
        )
        .unwrap();
    executor
        .execute("CREATE INDEX products_price_idx ON app.products(price);")
        .unwrap();
    executor
        .execute("CREATE VIEW app.product_view AS SELECT id, sku, price FROM app.products;")
        .unwrap();

    let rows = exec(
        &mut executor,
        "SELECT c.relname, n.nspname FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'app' ORDER BY c.relname;",
    );
    assert!(rows
        .iter()
        .any(|row| row[0] == Value::Text("products".into())));
    assert!(rows
        .iter()
        .any(|row| row[0] == Value::Text("product_view".into())));
    assert!(rows
        .iter()
        .any(|row| row[0] == Value::Text("products_price_idx".into())));

    let columns = exec(
        &mut executor,
        "SELECT column_name FROM information_schema.columns WHERE table_schema = 'app' AND table_name = 'products' ORDER BY ordinal_position;",
    );
    assert_eq!(columns.len(), 3);
    let constraints = exec(
        &mut executor,
        "SELECT constraint_type FROM information_schema.table_constraints WHERE table_schema = 'app' AND table_name = 'products';",
    );
    assert!(constraints
        .iter()
        .any(|row| row[0] == Value::Text("PRIMARY KEY".into())));
    assert!(constraints
        .iter()
        .any(|row| row[0] == Value::Text("UNIQUE".into())));

    executor
        .execute("ALTER TABLE app.products ADD CONSTRAINT products_sku_unique UNIQUE (sku);")
        .unwrap();
    let added = exec(
        &mut executor,
        "SELECT conname FROM pg_catalog.pg_constraint WHERE conname = 'products_sku_unique';",
    );
    assert!(added
        .iter()
        .any(|row| row[0] == Value::Text("products_sku_unique".into())));

    executor.execute("DROP VIEW app.product_view;").unwrap();
    executor.execute("DROP TABLE app.products;").unwrap();
    // The BIGSERIAL column left a backing sequence (`app.products_id_seq`);
    // with RESTRICT-as-default semantics the leftover sequence now blocks a
    // plain DROP SCHEMA, so the schema is dropped with CASCADE here.
    executor.execute("DROP SCHEMA app CASCADE;").unwrap();
    assert!(exec(
        &mut executor,
        "SELECT * FROM information_schema.tables WHERE table_schema = 'app';"
    )
    .is_empty());

    drop(executor);
    let _ = std::fs::remove_dir_all(&storage);
    let _ = std::fs::remove_dir_all(&wal);
}

#[test]
fn table_valued_settings_function_executes_through_relational_engine() {
    let (storage, wal) = unique_engine("settings-function");
    let engine = PlomidStorageEngine::create(&storage, &wal, 32).unwrap();
    let mut executor = Executor::new(engine).unwrap();
    let result = executor.execute("SELECT name, vartype, min_val::numeric AS min_val, max_val::numeric AS max_val, enumvals FROM pg_show_all_settings() WHERE context IN ('user', 'superuser');");
    assert!(result.is_ok(), "{result:?}");
    let dashboard = executor.execute("SELECT name, vartype, min_val::numeric AS min_val, max_val::numeric AS max_val, enumvals FROM pg_show_all_settings() WHERE context IN ('user', 'superuser') UNION ALL SELECT 'role', 'string', NULL, NULL, NULL;");
    assert!(dashboard.is_ok(), "{dashboard:?}");
    let nested = executor.execute("SELECT name, vartype, min_val::numeric AS min_val, max_val::numeric AS max_val, enumvals FROM (SELECT 'role'::text AS name, 'string'::text AS vartype, NULL AS min_val, NULL AS max_val, NULL::text[] AS enumvals UNION ALL SELECT name, vartype, min_val::numeric AS min_val, max_val::numeric AS max_val, enumvals FROM pg_show_all_settings() WHERE context IN ('user', 'superuser')) a;");
    assert!(nested.is_ok(), "{nested:?}");
    let json =
        executor.execute("SELECT row_to_json(t) FROM (SELECT 1 AS total, NULL AS active) t;");
    assert!(json.is_ok(), "{json:?}");
    drop(executor);
    let _ = std::fs::remove_dir_all(&storage);
    let _ = std::fs::remove_dir_all(&wal);
}

#[test]
fn catalog_relations_expose_complete_client_metadata_columns() {
    let (storage, wal) = unique_engine("catalog-shapes");
    let engine = PlomidStorageEngine::create(&storage, &wal, 32).unwrap();
    let mut executor = Executor::new(engine).unwrap();
    executor
        .execute("CREATE TABLE catalog_shape (id INTEGER DEFAULT 7, label VARCHAR(32));")
        .unwrap();
    assert!(executor
        .execute("SELECT c.relpartbound FROM pg_catalog.pg_class c;")
        .is_ok());
    let defaults = exec(&mut executor, "SELECT column_default FROM information_schema.columns WHERE table_name = 'catalog_shape' ORDER BY ordinal_position;");
    assert_eq!(defaults[0][0], Value::Text("7".into()));
    assert!(executor.execute("SELECT r.specific_name, r.routine_schema, r.routine_name, r.routine_type, r.data_type FROM information_schema.routines r;").is_ok());
    let oid = exec(
        &mut executor,
        "SELECT format('%I.%I', 'public', 'catalog_shape')::regclass::oid;",
    );
    assert!(matches!(oid[0][0], Value::Oid(_)));
    drop(executor);
    let _ = std::fs::remove_dir_all(&storage);
    let _ = std::fs::remove_dir_all(&wal);
}

#[cfg(test)]
mod network_type_integration {
    use super::*;

    #[test]
    fn int4multirange_constructor_produces_typed_multirange() {
        let (storage, wal) = unique_engine("int4multirange");
        let engine = PlomidStorageEngine::create(&storage, &wal, 32).unwrap();
        let mut executor = Executor::new(engine).unwrap();

        // Exact workload construct from JSON_ALL.sql:3668 — must execute without error.
        let rows = exec(
            &mut executor,
            "SELECT to_jsonb(int4multirange(int4range(1,5), int4range(10,20)));",
        );
        assert_eq!(rows.len(), 1);
        assert!(matches!(rows[0][0], Value::Jsonb(_)));
        // The rendered text is PostgreSQL-compatible.
        assert_eq!(rows[0][0].to_sql_text(), "\"{[1,5),[10,20)}\"");

        // to_json also works — same text wrapped in a Value::Json.
        let rows = exec(
            &mut executor,
            "SELECT to_json(int4multirange(int4range(1,5), int4range(10,20)));",
        );
        assert_eq!(rows.len(), 1);
        assert!(matches!(rows[0][0], Value::Json(_)));
        assert_eq!(rows[0][0].to_sql_text(), "\"{[1,5),[10,20)}\"");

        // Single-range multirange.
        let rows = exec(
            &mut executor,
            "SELECT to_jsonb(int4multirange(int4range(1,10)));",
        );
        assert!(matches!(rows[0][0], Value::Jsonb(_)));
        assert_eq!(rows[0][0].to_sql_text(), "\"{[1,10)}\"");

        // An int4multirange must be built from genuine int4range values; a
        // non-range argument is rejected rather than coerced into a multirange.
        let result = executor.execute("SELECT int4multirange(int4range(1,5), 7);");
        assert!(result.is_err(), "non-range argument must be rejected");
        let result = executor.execute("SELECT int4multirange(int4range(1,5), NULL);");
        assert!(result.is_err(), "NULL range argument must be rejected");
        drop(executor);
        let _ = std::fs::remove_dir_all(&storage);
        let _ = std::fs::remove_dir_all(&wal);
    }

    #[test]
    fn inet_array_text_input() {
        let (storage, wal) = unique_engine("inet-array");
        let engine = PlomidStorageEngine::create(&storage, &wal, 32).unwrap();
        let mut executor = Executor::new(engine).unwrap();

        // Exact workload construct from JSON_ALL.sql:3582 — must execute without error.
        let rows = exec(
            &mut executor,
            "SELECT to_jsonb(ARRAY['127.0.0.1'::inet, '192.168.1.1'::inet]);",
        );
        assert_eq!(rows.len(), 1);
        assert!(matches!(rows[0][0], Value::Jsonb(_)));
        assert_eq!(rows[0][0].to_sql_text(), "[\"127.0.0.1\",\"192.168.1.1\"]");

        // CIDR array also works.
        let rows = exec(
            &mut executor,
            "SELECT to_json(ARRAY['192.168.1.0/24'::cidr, '10.0.0.0/8'::cidr]);",
        );
        assert_eq!(rows.len(), 1);
        assert!(matches!(rows[0][0], Value::Json(_)));
        assert_eq!(
            rows[0][0].to_sql_text(),
            "[\"192.168.1.0/24\",\"10.0.0.0/8\"]"
        );
        // Valid IPv6 text input and prefix notation survive inet construction.
        let rows = exec(
            &mut executor,
            "SELECT to_jsonb(ARRAY['2001:db8::1'::inet, '::1'::inet]);",
        );
        assert_eq!(rows.len(), 1);
        assert!(matches!(rows[0][0], Value::Jsonb(_)));
        assert_eq!(rows[0][0].to_sql_text(), "[\"2001:db8::1\",\"::1\"]");
        let rows = exec(&mut executor, "SELECT to_json('10.0.0.0/8'::inet);");
        assert_eq!(rows.len(), 1);
        assert!(matches!(rows[0][0], Value::Json(_)));
        assert_eq!(rows[0][0].to_sql_text(), "\"10.0.0.0/8\"");

        // Invalid network input is still rejected — an inet must be a real address.
        let result = executor.execute("SELECT to_jsonb('not-an-ip'::inet);");
        assert!(result.is_err(), "invalid inet input must be rejected");
        let result = executor.execute("SELECT to_jsonb('127.0.0.1/99'::inet);");
        assert!(
            result.is_err(),
            "netmask wider than the address family must be rejected"
        );

        drop(executor);
        let _ = std::fs::remove_dir_all(&storage);
        let _ = std::fs::remove_dir_all(&wal);
    }

    #[test]
    fn enum_array_typed_values() {
        let (storage, wal) = unique_engine("enum-array");
        let engine = PlomidStorageEngine::create(&storage, &wal, 32).unwrap();
        let mut executor = Executor::new(engine).unwrap();

        executor
            .execute("CREATE TYPE status_enum AS ENUM ('pending', 'active', 'completed');")
            .unwrap();

        // Exact workload construct from JSON_ALL.sql:3648 — must execute without error.
        let rows = exec(
            &mut executor,
            "SELECT to_jsonb(ARRAY['pending'::status_enum, 'active'::status_enum]);",
        );
        assert_eq!(rows.len(), 1);
        assert!(matches!(rows[0][0], Value::Jsonb(_)));
        assert_eq!(rows[0][0].to_sql_text(), "[\"pending\",\"active\"]");

        // A single declared enum label round-trips through to_json as a JSON
        // string (the label), matching PostgreSQL.
        let rows = exec(&mut executor, "SELECT to_json('completed'::status_enum);");
        assert_eq!(rows.len(), 1);
        assert!(matches!(rows[0][0], Value::Json(_)));
        assert_eq!(rows[0][0].to_sql_text(), "\"completed\"");

        // Element type resolution still coerces every element to the inferred
        // type — a value that cannot be coerced is rejected rather than stored
        // as arbitrary text.
        let result = executor.execute("SELECT ARRAY[42, 'not-an-int'];");
        assert!(result.is_err(), "non-coercible element must be rejected");
        drop(executor);
        let _ = std::fs::remove_dir_all(&storage);
        let _ = std::fs::remove_dir_all(&wal);
    }
}
