//
// © 2026 PLOMID Technology Solutions
//
// PLOMID
// Platform for Modern Intelligence and Data
//
// Author: Sainath Sapa
// GitHub: https://github.com/sainathsapa
//
// Licensed under the Apache License, Version 2.0;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//! PLOMID ART index benchmarks: insert, lookup, delete, and memory.
//!
//! Run with: `cargo bench -p plomid-index --bench art`.
//!
//! The harness is deliberately dependency-free (no criterion): the report needs
//! operations/sec *and* p50/p95/p99 latencies, which are measured directly with
//! `Instant` over a per-operation sample. This matches the plain-harness style
//! used by `crates/columnar/benches/flush_pipeline.rs`, and avoids adding a
//! dependency for numbers criterion does not report directly.
//!
//! Datasets are generated by a deterministic splitmix64 PRNG, so a run is
//! reproducible from its seed alone.
//!
//! Sizes: 1K, 10K, 100K, and 1M keys. The 1M size is exercised for the
//! fixed-width shapes (random, sequential) where memory stays bounded; the
//! wide variable-length and binary shapes run up to 100K. Every number printed
//! below was produced by running this benchmark, not estimated.

use plomid_core::RowId;
use plomid_index::{ArtIndex, IndexKind};
use std::time::Instant;

/// Deterministic splitmix64 PRNG.
///
/// Written out here on purpose: an index benchmark should not force a
/// random-number dependency into the crate graph.
struct Rng(u64);

impl Rng {
    /// Creates a generator with the given seed.
    fn new(seed: u64) -> Self {
        Self(seed)
    }

    /// Returns the next pseudo-random `u64`.
    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Returns a pseudo-random index in `0..bound`.
    fn below(&mut self, bound: usize) -> usize {
        (self.next_u64() % bound as u64) as usize
    }
}

/// The key shapes the ART core is expected to serve.
#[derive(Clone, Copy, Debug)]
enum Shape {
    /// Uniformly random 8-byte keys: worst case for path compression.
    Random,
    /// Ascending 8-byte keys: best case for a sorted run, worst case for
    /// fanout (consecutive keys share seven leading bytes).
    Sequential,
    /// Keys sharing a long common prefix: exercises prefix handling.
    CommonPrefix,
    /// Keys of varying length: exercises short/long key handling.
    Variable,
    /// Keys containing `0x00` and `0xFF`: binary keys, never treated as text.
    Binary,
}

impl Shape {
    /// Stable label used in the report.
    fn name(self) -> &'static str {
        match self {
            Self::Random => "random",
            Self::Sequential => "sequential",
            Self::CommonPrefix => "common-prefix",
            Self::Variable => "variable-length",
            Self::Binary => "binary",
        }
    }

    /// Builds `count` distinct keys for this shape.
    fn keys(self, count: usize, seed: u64) -> Vec<Vec<u8>> {
        let mut rng = Rng::new(seed);
        match self {
            Self::Random => (0..count)
                .map(|_| rng.next_u64().to_be_bytes().to_vec())
                .collect(),
            Self::Sequential => (0..count as u64)
                .map(|value| value.to_be_bytes().to_vec())
                .collect(),
            Self::CommonPrefix => (0..count as u64)
                // A 32-byte constant prefix, then a counter: every key shares
                // the first 32 bytes.
                .map(|value| {
                    let mut key = b"plomid/common/prefix/00000000/".to_vec();
                    key.extend_from_slice(&value.to_be_bytes());
                    key
                })
                .collect(),
            Self::Variable => {
                // Lengths cycle through 1..=61 bytes so both short keys
                // (single-byte terminals) and long keys appear. Random bytes
                // can collide, so duplicates are skipped: the unique-index
                // bench needs `count` distinct keys. Every key carries a
                // length tag in its last byte, which no miss probe touches.
                let mut seen = std::collections::HashSet::with_capacity(count);
                let mut keys = Vec::with_capacity(count);
                let mut index = 0usize;
                while keys.len() < count {
                    let len = 1 + index % 61;
                    let tag = (index % 256) as u8;
                    let mut key: Vec<u8> =
                        (0..len).map(|_| (rng.next_u64() & 0xff) as u8).collect();
                    key[len - 1] = tag;
                    index += 1;
                    if seen.insert(key.clone()) {
                        keys.push(key);
                    }
                }
                keys
            }
            Self::Binary => (0..count as u64)
                .map(|value| {
                    // 0x00 and 0xFF at both ends, arbitrary bytes in the middle.
                    let mut key = vec![0x00, 0xFF];
                    key.extend_from_slice(&value.to_be_bytes());
                    key.push(0xFF);
                    key
                })
                .collect(),
        }
    }
}

/// Latency of one operation in nanoseconds.
type Nanos = u64;

/// Returns the requested percentile from an unsorted latency sample.
///
/// Nearest-rank method: the first sample that is at or above the requested
/// share of the sorted sample.
fn percentile(samples: &mut [Nanos], pct: f64) -> Nanos {
    if samples.is_empty() {
        return 0;
    }
    samples.sort_unstable();
    let rank = ((samples.len() as f64) * pct).ceil() as usize;
    let index = rank.saturating_sub(1).min(samples.len() - 1);
    samples[index]
}

/// Prints one measured operation.
fn report(label: &str, ops: usize, elapsed_s: f64, samples: &mut [Nanos]) {
    let per_sec = if elapsed_s > 0.0 {
        ops as f64 / elapsed_s
    } else {
        0.0
    };
    let mean_us = if samples.is_empty() {
        0.0
    } else {
        samples.iter().sum::<Nanos>() as f64 / samples.len() as f64 / 1_000.0
    };
    println!(
        "  {label:<34} {ops:>8} ops {per_sec:>12.0} ops/s  mean {mean_us:>7.3} us  \
         p50 {:>7.3} us  p95 {:>7.3} us  p99 {:>7.3} us",
        percentile(samples, 0.50) as f64 / 1_000.0,
        percentile(samples, 0.95) as f64 / 1_000.0,
        percentile(samples, 0.99) as f64 / 1_000.0,
    );
}

/// Builds an index from `keys`, measuring insert latency per operation.
///
/// Returns the index plus the latency sample.
fn build_index(keys: &[Vec<u8>]) -> (ArtIndex, Vec<Nanos>, f64) {
    let mut index = ArtIndex::unique();
    let mut samples = Vec::with_capacity(keys.len());
    let start = Instant::now();
    for (offset, key) in keys.iter().enumerate() {
        let op = Instant::now();
        // RowId is `offset + 1`: RowIds stay distinct and non-zero, which is
        // all a unique index requires. They are logical ids, never offsets.
        index
            .insert(key.as_slice(), RowId::new(offset as u64 + 1))
            .expect("unique keys, one RowId each");
        samples.push(op.elapsed().as_nanos() as Nanos);
    }
    let elapsed = start.elapsed().as_secs_f64();
    (index, samples, elapsed)
}

/// Runs the full measurement set for one shape and size.
fn bench_shape(shape: Shape, count: usize) {
    let keys = shape.keys(count, 0x5EED_1234);
    println!();
    println!("{} — {count} keys", shape.name());

    let (index, mut insert_samples, insert_secs) = build_index(&keys);
    report("insert", count, insert_secs, &mut insert_samples);

    // Point lookups on present keys, sampled so 1M-key runs stay quick.
    let mut rng = Rng::new(0xA11CE);
    let probes = count.min(100_000);
    let mut hit_samples = Vec::with_capacity(probes);
    let start = Instant::now();
    for _ in 0..probes {
        let key = &keys[rng.below(count)];
        let op = Instant::now();
        let found = index.lookup(key.as_slice());
        assert!(found.is_some(), "present key must be found");
        hit_samples.push(op.elapsed().as_nanos() as Nanos);
    }
    let hit_secs = start.elapsed().as_secs_f64();
    report("lookup (hit)", probes, hit_secs, &mut hit_samples);

    // Point lookups on absent keys: the miss path must be just as cheap.
    // Miss probes extend a stored key by one extra byte, which forces the
    // walk past a terminal into a missing child. Membership against the
    // stored set guarantees absence (a longer stored key could otherwise
    // equal the extension, especially for the variable-length shape), and
    // the retry loop keeps the probe count exact.
    let stored: std::collections::HashSet<&[u8]> = keys.iter().map(Vec::as_slice).collect();
    let mut miss_samples = Vec::with_capacity(probes);
    let start = Instant::now();
    for _ in 0..probes {
        let key = loop {
            let mut candidate = keys[rng.below(count)].clone();
            candidate.push((rng.next_u64() & 0xff) as u8);
            if !stored.contains(candidate.as_slice()) {
                break candidate;
            }
        };
        let op = Instant::now();
        let found = index.lookup(key.as_slice());
        assert!(found.is_none(), "extended key must be absent");
        miss_samples.push(op.elapsed().as_nanos() as Nanos);
    }
    let miss_secs = start.elapsed().as_secs_f64();
    report("lookup (miss)", probes, miss_secs, &mut miss_samples);

    // Structural report before deletion: node family mix and bytes per entry.
    let stats = index.stats();
    println!(
        "  {:<34} keys {} nodes {} (n4 {} n16 {} n48 {} n256 {}) depth {} \
         ≈ {:.1} bytes/entry",
        "structure",
        stats.keys,
        stats.nodes,
        stats.node_counts[0],
        stats.node_counts[1],
        stats.node_counts[2],
        stats.node_counts[3],
        stats.max_depth,
        stats.bytes as f64 / stats.entries.max(1) as f64,
    );

    // Delete every key, measuring latency and checking the tree drains cleanly.
    let mut index = index;
    let deleted = count;
    let mut delete_samples = Vec::with_capacity(deleted);
    let start = Instant::now();
    for (offset, key) in keys.iter().enumerate() {
        let op = Instant::now();
        index
            .delete(key.as_slice(), RowId::new(offset as u64 + 1))
            .expect("delete cannot fail on a well-formed key");
        delete_samples.push(op.elapsed().as_nanos() as Nanos);
    }
    let delete_secs = start.elapsed().as_secs_f64();
    report("delete", deleted, delete_secs, &mut delete_samples);

    assert!(index.is_empty(), "every inserted key must be deleted");
    let end_stats = index.stats();
    println!(
        "  {:<34} keys {} nodes {} depth {}",
        "after delete", end_stats.keys, end_stats.nodes, end_stats.max_depth
    );
}

/// Measures ART reconstruction: the startup cost of rebuilding the derived
/// runtime index from the ordered entries a durable index generation yields.
///
/// This is the exact operation a recovery performs after the persistent
/// authority reaches its recovered state, so the number is the ART share of
/// startup. The entries are the same keys used elsewhere, each paired with the
/// distinct `RowId` the durable B+Tree stores (`offset + 1`).
fn bench_rebuild(shape: Shape, count: usize) {
    let keys = shape.keys(count, 0x5EED_1234);
    let entries: Vec<(Vec<u8>, RowId)> = keys
        .iter()
        .enumerate()
        .map(|(offset, key)| (key.clone(), RowId::new(offset as u64 + 1)))
        .collect();
    println!("reconstruct — {} — {count} keys", shape.name());
    let start = Instant::now();
    let index = ArtIndex::rebuild_from_entries(IndexKind::Unique, entries)
        .expect("unique keys reconstruct into a valid ART");
    let elapsed = start.elapsed().as_secs_f64();
    assert_eq!(index.len(), count, "reconstruction preserves every entry");
    // A reconstruction is one whole-batch startup operation, so the meaningful
    // numbers are total duration, keys/sec, and ns/key — not per-operation
    // percentiles, which do not exist for a single batch call.
    let keys_per_sec = if elapsed > 0.0 {
        count as f64 / elapsed
    } else {
        0.0
    };
    println!(
        "  {:<34} {:>8} keys {:>9.3} ms {:>12.0} keys/s {:>8.1} ns/key",
        "reconstruct",
        count,
        elapsed * 1_000.0,
        keys_per_sec,
        elapsed * 1_000_000_000.0 / count as f64
    );
}

fn main() {
    println!("PLOMID adaptive radix tree (ART) benchmarks");
    for shape in [
        Shape::Random,
        Shape::Sequential,
        Shape::CommonPrefix,
        Shape::Variable,
        Shape::Binary,
    ] {
        let wide = matches!(shape, Shape::Random | Shape::Sequential);
        for count in [1_000usize, 10_000, 100_000] {
            bench_shape(shape, count);
        }
        if wide {
            bench_shape(shape, 1_000_000);
        }
    }

    // Startup reconstruction: the derived ART rebuilt from the persistent
    // authority's ordered entries after recovery.
    println!();
    println!("PLOMID ART reconstruction (startup) benchmarks");
    for shape in [Shape::Random, Shape::Sequential, Shape::Binary] {
        for count in [1_000usize, 10_000, 100_000] {
            bench_rebuild(shape, count);
        }
    }
    println!();
    println!("Benchmarks complete.");
}
