[package]
name = "plomid-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Core primitives and shared kernel types for PLOMID."

[dependencies]

[lib]
path = "src/lib.rs"

[lints]
workspace = true
